#!/usr/bin/env sh
# Lighthouse agent installer.
#
# Usage:
#   curl -fsSL https://lighthouse.statusharbor.io/install.sh \
#     | LIGHTHOUSE_TOKEN=<token-from-console> sh
#
# This script:
#   1. Detects OS/arch.
#   2. Downloads the latest signed release binary from GitHub Releases.
#   3. Verifies the SHA256 checksum.
#   4. Writes lighthouse.yaml with the supplied token.
#   5. Installs a systemd unit (Linux) or launchd plist (macOS), or prints
#      run instructions on unsupported init systems.
#
# All steps are POSIX sh — no bashisms — so it runs on minimal Alpine /
# busybox images that ops shops often use for monitoring boxes.

set -eu

REPO="statusharbor/lighthouse"
INSTALL_DIR="${LIGHTHOUSE_INSTALL_DIR:-/usr/local/bin}"
DATA_DIR="${LIGHTHOUSE_DATA_DIR:-/var/lib/lighthouse}"
CONFIG_PATH="${LIGHTHOUSE_CONFIG:-/etc/lighthouse/lighthouse.yaml}"

die() { printf '\nlighthouse install: %s\n' "$1" >&2; exit 1; }
note() { printf '==> %s\n' "$1"; }

[ -n "${LIGHTHOUSE_TOKEN:-}" ] || die "LIGHTHOUSE_TOKEN environment variable is required (mint one from your Status Harbor Console)"

# --- detect platform -------------------------------------------------------
uname_s=$(uname -s 2>/dev/null || echo unknown)
uname_m=$(uname -m 2>/dev/null || echo unknown)

case "$uname_s" in
    Linux)  os="linux" ;;
    Darwin) os="darwin" ;;
    *)      die "unsupported OS: $uname_s" ;;
esac

case "$uname_m" in
    x86_64|amd64)  arch="amd64" ;;
    aarch64|arm64) arch="arm64" ;;
    *)             die "unsupported architecture: $uname_m" ;;
esac

note "platform: ${os}_${arch}"

# --- pick a downloader -----------------------------------------------------
if command -v curl >/dev/null 2>&1; then
    fetch() { curl -fsSL "$1" -o "$2"; }
elif command -v wget >/dev/null 2>&1; then
    fetch() { wget -q "$1" -O "$2"; }
else
    die "neither curl nor wget found"
fi

# --- discover latest release ----------------------------------------------
note "discovering latest release"
api_url="https://api.github.com/repos/${REPO}/releases/latest"
tmp_release=$(mktemp)
trap 'rm -f "$tmp_release"' EXIT
fetch "$api_url" "$tmp_release"

# Plain shell parsing — avoids requiring jq on minimal hosts.
tag=$(grep -m1 '"tag_name"' "$tmp_release" | sed 's/.*"tag_name": *"\([^"]*\)".*/\1/')
[ -n "$tag" ] || die "could not parse tag_name from GitHub release JSON"
note "version: $tag"

binary_name="lighthouse_${os}_${arch}"
binary_url="https://github.com/${REPO}/releases/download/${tag}/${binary_name}"
checksum_url="https://github.com/${REPO}/releases/download/${tag}/checksums.txt"

# --- download + verify -----------------------------------------------------
tmp_bin=$(mktemp)
tmp_sums=$(mktemp)
trap 'rm -f "$tmp_release" "$tmp_bin" "$tmp_sums"' EXIT

note "downloading $binary_name"
fetch "$binary_url" "$tmp_bin"
fetch "$checksum_url" "$tmp_sums"

if command -v sha256sum >/dev/null 2>&1; then
    actual=$(sha256sum "$tmp_bin" | awk '{print $1}')
elif command -v shasum >/dev/null 2>&1; then
    actual=$(shasum -a 256 "$tmp_bin" | awk '{print $1}')
else
    die "no sha256 utility found (sha256sum or shasum required)"
fi

expected=$(grep " ${binary_name}\$" "$tmp_sums" | awk '{print $1}' || true)
[ -n "$expected" ] || die "${binary_name} not in checksums.txt"
[ "$actual" = "$expected" ] || die "checksum mismatch (expected $expected, got $actual)"
note "checksum verified"

# --- install ---------------------------------------------------------------
sudo_cmd=""
if [ "$(id -u)" -ne 0 ]; then
    if command -v sudo >/dev/null 2>&1; then
        sudo_cmd="sudo"
    else
        die "must run as root or have sudo (writing to ${INSTALL_DIR})"
    fi
fi

note "installing to ${INSTALL_DIR}/lighthouse"
$sudo_cmd install -m 0755 "$tmp_bin" "${INSTALL_DIR}/lighthouse"

# Write config + ensure data dir.
$sudo_cmd mkdir -p "$(dirname "$CONFIG_PATH")" "$DATA_DIR"
note "writing config to ${CONFIG_PATH}"
# shellcheck disable=SC2024
$sudo_cmd sh -c "cat > '${CONFIG_PATH}'" <<EOF
# Lighthouse agent configuration. Generated by install.sh.
token: ${LIGHTHOUSE_TOKEN}

agent:
  data_dir: ${DATA_DIR}
  log_level: info
EOF
$sudo_cmd chmod 0600 "$CONFIG_PATH"

# --- service unit ----------------------------------------------------------
case "$os" in
    linux)
        if [ -d /run/systemd/system ]; then
            note "installing systemd unit"
            $sudo_cmd sh -c "cat > /etc/systemd/system/lighthouse.service" <<EOF
[Unit]
Description=Status Harbor Lighthouse Agent
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=${INSTALL_DIR}/lighthouse -config ${CONFIG_PATH}
# Restart on crash, NOT on clean exit. The agent exits with 0 when the
# Console says the lighthouse has been deleted (401/410); restart=always
# would keep relaunching it into an immediate exit forever.
Restart=on-failure
RestartSec=5
NoNewPrivileges=true
ProtectSystem=strict
ProtectHome=true
ReadWritePaths=${DATA_DIR}
PrivateTmp=true

[Install]
WantedBy=multi-user.target
EOF
            $sudo_cmd systemctl daemon-reload
            $sudo_cmd systemctl enable --now lighthouse.service
            note "systemd service started: systemctl status lighthouse"
        else
            note "systemd not detected — start manually as root: sudo ${INSTALL_DIR}/lighthouse -config ${CONFIG_PATH}"
            note "(the config at ${CONFIG_PATH} is mode 0600 root:root because it carries the agent token)"
        fi
        ;;
    darwin)
        plist_path="/Library/LaunchDaemons/io.statusharbor.lighthouse.plist"
        log_dir="/var/log/lighthouse"
        $sudo_cmd mkdir -p "$log_dir"
        note "installing launchd daemon at $plist_path"
        # shellcheck disable=SC2024
        $sudo_cmd sh -c "cat > '$plist_path'" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>io.statusharbor.lighthouse</string>
    <key>ProgramArguments</key>
    <array>
        <string>${INSTALL_DIR}/lighthouse</string>
        <string>-config</string>
        <string>${CONFIG_PATH}</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <!-- Keep alive on crash but NOT on clean exit. The agent exits with 0
         when the Console says the lighthouse has been deleted; an
         unconditional KeepAlive=true would relaunch it into an immediate
         exit forever. -->
    <key>KeepAlive</key>
    <dict>
        <key>SuccessfulExit</key>
        <false/>
        <key>Crashed</key>
        <true/>
    </dict>
    <key>StandardOutPath</key>
    <string>${log_dir}/lighthouse.log</string>
    <key>StandardErrorPath</key>
    <string>${log_dir}/lighthouse.err.log</string>
    <key>WorkingDirectory</key>
    <string>${DATA_DIR}</string>
</dict>
</plist>
EOF
        $sudo_cmd chmod 0644 "$plist_path"
        $sudo_cmd chown root:wheel "$plist_path"
        # bootout first in case a previous version is loaded; ignore the
        # error when nothing is currently registered.
        $sudo_cmd launchctl bootout system "$plist_path" 2>/dev/null || true
        $sudo_cmd launchctl bootstrap system "$plist_path"
        note "launchd daemon started: sudo launchctl print system/io.statusharbor.lighthouse"
        note "logs: $log_dir/lighthouse.log"
        ;;
esac

note "lighthouse installed. Visit your Status Harbor Console to verify the agent is online."
