{{- if not .Values.existingSecret.name }}
{{- if not .Values.token }}
{{- fail "lighthouse: provide either .Values.token or .Values.existingSecret.name" }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-token" (include "lighthouse.fullname" .) }}
  labels:
    {{- include "lighthouse.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ .Values.token | quote }}
{{- end }}
